### ISSUE TITLE
Tracker for apps using old DConf access method

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#1040]
This should be the full list of applications having access to GSettings in the host's DConf database by punching a hole in the sandbox.

Applications should instead rely on the xdg-desktop-portal "settings" portal, to get access to global or lockdown settings, and a keyfile GSettings backend.

If xdg-desktop-portal is new enough on the host (1.1.0 or newer), and the application's runtime includes GLib 2.60 (GNOME 3.32 or newer), then this should automatically work once dconf access is removed from the application's manifest.

## Runtimes with host DConf access

 * [x] [org.kde.Platform](https://github.com/KDE/flatpak-kde-runtime/)

## Applications with host DConf access

 * [x] [org.gnome.Recipes](https://github.com/flathub/org.gnome.Recipes)
 * [x] [com.uploadedlobster.peek](https://github.com/flathub/com.uploadedlobster.peek)
 * [x] [com.vinszent.GnomeTwitch](https://github.com/flathub/com.vinszent.GnomeTwitch)
 * [x] [org.gnome.FeedReader](https://github.com/flathub/org.gnome.FeedReader)
 * [x] [io.github.Pithos](https://github.com/flathub/io.github.Pithos)
 * [x] [io.github.GnomeMpv](https://github.com/flathub/io.github.GnomeMpv)
 * [x] [org.DolphinEmu.dolphin-emu](https://github.com/flathub/org.DolphinEmu.dolphin-emu)
 * [x] [org.baedert.corebird](https://github.com/flathub/org.baedert.corebird)
 * [x] [nl.openoffice.bluefish](https://github.com/flathub/nl.openoffice.bluefish)
 * [x] [com.github.needleandthread.vocal](https://github.com/flathub/com.github.needleandthread.vocal)
 * [x] [org.darktable.Darktable](https://github.com/flathub/org.darktable.Darktable)
 * [x] ~~[org.gnome.Nautilus](https://github.com/flathub/org.gnome.Nautilus)~~
 * [x] [org.audacityteam.Audacity](https://github.com/flathub/org.audacityteam.Audacity)
 * [x] [org.gnome.Lollypop](https://github.com/flathub/org.gnome.Lollypop)
 * [x] [org.mypaint.MyPaint](https://github.com/flathub/org.mypaint.MyPaint)
 * [x] [org.gnome.Eolie](https://github.com/flathub/org.gnome.Eolie)
 * [x] [org.gnome.Polari](https://github.com/flathub/org.gnome.Polari)
 * [x] [com.github.dahenson.agenda](https://github.com/flathub/com.github.dahenson.agenda)
 * [x] [org.gnome.frogr](https://github.com/flathub/org.gnome.frogr)
 * [x] [org.gnucash.GnuCash](https://github.com/flathub/org.gnucash.GnuCash)
 * [x] ~~[[io.elementary.code](https://github.com/flathub/io.elementary.code)~~[
 * [x] [ch.x29a.playitslowly](https://github.com/flathub/ch.x29a.playitslowly)
 * [x] [com.github.philip_scott.notes-up](https://github.com/flathub/com.github.philip_scott.notes-up)
 * [x] [org.gnome.Calendar](https://github.com/flathub/org.gnome.Calendar)
 * [x] [org.gnome.eog](https://github.com/flathub/org.gnome.eog)
 * [x] [org.gnome.gedit](https://github.com/flathub/org.gnome.gedit)
 * [x] ~~[org.gnome.iagno](https://github.com/flathub/org.gnome.iagno)~~
 * [x] [org.gnome.Glade](https://github.com/flathub/org.gnome.Glade)
 * [ ] [ca.desrt.dconf-editor](https://github.com/flathub/ca.desrt.dconf-editor)
 * [x] [org.freedesktop.Bustle](https://github.com/flathub/org.freedesktop.Bustle)
 * [x] [com.transmissionbt.Transmission](https://github.com/flathub/com.transmissionbt.Transmission)
 * [x] [org.filezillaproject.Filezilla](https://github.com/flathub/org.filezillaproject.Filezilla)
 * [x] [com.slack.Slack](https://github.com/flathub/com.slack.Slack)
 * [x] [com.github.wwmm.pulseeffects](https://github.com/flathub/com.github.wwmm.pulseeffects)
 * [x] [org.videolan.VLC](https://github.com/flathub/org.videolan.VLC)
 * [x] [org.gnome.Photos](https://github.com/flathub/org.gnome.Photos)
 * [x] [net.pcsx2.PCSX2](https://github.com/flathub/net.pcsx2.PCSX2)
 * [ ] [ca._0ldsk00l.Nestopia](https://github.com/flathub/ca._0ldsk00l.Nestopia)
 * [x] [de.haeckerfelix.gradio](https://github.com/flathub/de.haeckerfelix.gradio)
 * [x] [com.github.gkarsay.parlatype](https://github.com/flathub/com.github.gkarsay.parlatype)
 * [x] [com.github.philip_scott.spice-up](https://github.com/flathub/com.github.philip_scott.spice-up)
 * [x] [org.gnome.Geary](https://github.com/flathub/org.gnome.Geary)
 * [x] [org.gnome.Hitori](https://github.com/flathub/org.gnome.Hitori)
 * [x] [org.pitivi.Pitivi](https://github.com/flathub/org.pitivi.Pitivi)
 * [x] [org.gnome.Builder](https://github.com/flathub/org.gnome.Builder)
 * [x] [de.manuel_kehl.go-for-it](https://github.com/flathub/de.manuel_kehl.go-for-it)
 * [x] [org.gnome.clocks](https://github.com/flathub/org.gnome.clocks)
 * [x] [fr.free.Homebank](https://github.com/flathub/fr.free.Homebank)
 * [x] [com.frac_tion.teleport](https://github.com/flathub/com.frac_tion.teleport)
 * [x] [org.gnome.Games](https://github.com/flathub/org.gnome.Games)
 * [x] [com.github.babluboy.bookworm](https://github.com/flathub/com.github.babluboy.bookworm)
 * [x] ~~[org.gnome.bijiben](https://github.com/flathub/org.gnome.bijiben)~~
 * [x] [org.gnome.Calculator](https://github.com/flathub/org.gnome.Calculator)
 * [x] [org.gnome.Characters](https://github.com/flathub/org.gnome.Characters)
 * [x] [org.gnome.Dictionary](https://github.com/flathub/org.gnome.Dictionary)
 * [x] [org.gnome.Maps](https://github.com/flathub/org.gnome.Maps)
 * [x] [org.gnome.Rhythmbox3](https://github.com/flathub/org.gnome.Rhythmbox3)
 * [x] [com.github.bajoja.indicator-kdeconnect](https://github.com/flathub/com.github.bajoja.indicator-kdeconnect)
 * [x] [org.gnome.Books](https://github.com/flathub/org.gnome.Books)
 * [x] [org.gnome.Evince](https://github.com/flathub/org.gnome.Evince)
 * [x] [org.gnome.Documents](https://github.com/flathub/org.gnome.Documents)
 * [x] [org.gnome.gitg](https://github.com/flathub/org.gnome.gitg)
 * [x] [org.gnome.Todo](https://github.com/flathub/org.gnome.Todo)
 * [x] [org.gnome.Totem](https://github.com/flathub/org.gnome.Totem)
 * [x] [org.gnome.Weather](https://github.com/flathub/org.gnome.Weather)
 * [x] [org.gnome.Devhelp](https://github.com/flathub/org.gnome.Devhelp)
 * [x] ~~[org.gnome.Epiphany](https://github.com/flathub/org.gnome.Epiphany)~~
 * [x] [org.libreoffice.LibreOffice](https://github.com/flathub/org.libreoffice.LibreOffice)
 * [x] [org.gnome.Fractal](https://github.com/flathub/org.gnome.Fractal)
 * [x] [net.mediaarea.MediaInfo](https://github.com/flathub/net.mediaarea.MediaInfo)
 * [x] [work.openpaper.Paperwork](https://github.com/flathub/work.openpaper.Paperwork)
 * [x] [com.github.geigi.cozy](https://github.com/flathub/com.github.geigi.cozy)
 * [x] [com.github.birros.WebArchives](https://github.com/flathub/com.github.birros.WebArchives)
 * [x] [cx.ring.Ring](https://github.com/flathub/cx.ring.Ring)
 * [x] [org.gnome.quadrapassel](https://github.com/flathub/org.gnome.quadrapassel)
 * [x] [org.gnome.Aisleriot](https://github.com/flathub/org.gnome.Aisleriot)
 * [x] [org.gnome.Gnote](https://github.com/flathub/org.gnome.Gnote)
 * [x] [org.gnome.Genius](https://github.com/flathub/org.gnome.Genius)
 * [x] [org.gnome.tetravex](https://github.com/flathub/org.gnome.tetravex)
 * [x] [io.github.betaflight.BetaflightConfigurator](https://github.com/flathub/io.github.betaflight.BetaflightConfigurator)
 * [x] [com.github.paolostivanin.OTPClient](https://github.com/flathub/com.github.paolostivanin.OTPClient)
 * [x] [com.github.lainsce.notejot](https://github.com/flathub/com.github.lainsce.notejot)
 * [x] [org.gnome.ghex](https://github.com/flathub/org.gnome.ghex)
 * [x] [com.google.AndroidStudio](https://github.com/flathub/com.google.AndroidStudio)
 * [x] [org.gnome.meld](https://github.com/flathub/org.gnome.meld)
 * [x] [com.github.robertsanseries.ciano](https://github.com/flathub/com.github.robertsanseries.ciano)
 * [x] [io.github.jliljebl.Flowblade](https://github.com/flathub/io.github.jliljebl.Flowblade)
 * [x] [com.github.fabiocolacio.marker](https://github.com/flathub/com.github.fabiocolacio.marker)
 * [x] [net.bartkessels.getit](https://github.com/flathub/net.bartkessels.getit)
 * [x] [com.github.cassidyjames.dippi](https://github.com/flathub/com.github.cassidyjames.dippi)
 * [x] [com.github.bitseater.weather](https://github.com/flathub/com.github.bitseater.weather)
 * [x] [org.gnome.dfeet](https://github.com/flathub/org.gnome.dfeet)
 * [x] [com.github.donadigo.appeditor](https://github.com/flathub/com.github.donadigo.appeditor)
 * [ ] [org.gabmus.hydrapaper](https://github.com/flathub/org.gabmus.hydrapaper)
 * [x] [net.sf.VICE](https://github.com/flathub/net.sf.VICE)
 * [x] [net.poedit.Poedit](https://github.com/flathub/net.poedit.Poedit)
 * [x] [org.gnome.glabels-3](https://github.com/flathub/org.gnome.glabels-3)
 * [x] [com.github.bilelmoussaoui.Authenticator](https://github.com/flathub/com.github.bilelmoussaoui.Authenticator)
 * [x] [org.freedesktop.GstDebugViewer](https://github.com/flathub/org.freedesktop.GstDebugViewer)
 * [x] [io.github.jkozera.ZevDocs](https://github.com/flathub/io.github.jkozera.ZevDocs)
 * [x] [com.github.lainsce.coin](https://github.com/flathub/com.github.lainsce.coin)
 * [x] [com.github.alecaddd.sequeler](https://github.com/flathub/com.github.alecaddd.sequeler)
 * [x] [uk.co.mangobrain.Infector](https://github.com/flathub/uk.co.mangobrain.Infector)
 * [x] [com.github.lainsce.yishu](https://github.com/flathub/com.github.lainsce.yishu)
 * [x] [org.gnome.Music](https://github.com/flathub/org.gnome.Music)
 * [x] [org.mozilla.Thunderbird](https://github.com/flathub/org.mozilla.Thunderbird)
 * [x] [org.remmina.Remmina](https://github.com/flathub/org.remmina.Remmina)
 * [ ] [com.lettier.movie-monad](https://github.com/flathub/com.lettier.movie-monad)
 * [x] [org.gnome.Contacts](https://github.com/flathub/org.gnome.Contacts)
 * [x] [de.haeckerfelix.Fragments](https://github.com/flathub/de.haeckerfelix.Fragments)
 * [x] [de.wolfvollprecht.UberWriter](https://github.com/flathub/de.wolfvollprecht.UberWriter)
 * [x] [com.ozmartians.VidCutter](https://github.com/flathub/com.ozmartians.VidCutter)
 * [x] [org.gajim.Gajim](https://github.com/flathub/org.gajim.Gajim)
 * [x] [io.github.quodlibet.QuodLibet](https://github.com/flathub/io.github.quodlibet.QuodLibet)
 * [ ] [org.gnome.Boxes](https://github.com/flathub/org.gnome.Boxes)
 * [x] [io.github.janbar.noson](https://github.com/flathub/io.github.janbar.noson)
 * [x] [com.github.mdh34.quickdocs](https://github.com/flathub/com.github.mdh34.quickdocs)
 * [x] [com.github.mdh34.hackup](https://github.com/flathub/com.github.mdh34.hackup)
 * [x] [com.endlessm.photos](https://github.com/flathub/com.endlessm.photos)
 * [x] [net.sf.fuse_emulator](https://github.com/flathub/net.sf.fuse_emulator)
 * [x] [com.github.muriloventuroso.easyssh](https://github.com/flathub/com.github.muriloventuroso.easyssh)
 * [x] [com.axosoft.GitKraken](https://github.com/flathub/com.axosoft.GitKraken)
 * [ ] [com.github.marktext.marktext](https://github.com/flathub/com.github.marktext.marktext)
 * [x] [fr.handbrake.ghb](https://github.com/flathub/fr.handbrake.ghb)
 * [x] [edu.stanford.Almond](https://github.com/flathub/edu.stanford.Almond)
 * [x] [org.gnome.Chess](https://github.com/flathub/org.gnome.Chess)
 * [x] ~~[[com.github.eudaldgr.elements](https://github.com/flathub/com.github.eudaldgr.elements)~~[
 * [x] [org.gnome.Podcasts](https://github.com/flathub/org.gnome.Podcasts)
 * [x] [com.github.bleakgrey.tootle](https://github.com/flathub/com.github.bleakgrey.tootle)
 * [ ] [org.laptop.TurtleArtActivity](https://github.com/flathub/org.laptop.TurtleArtActivity)
 * [x] [org.synfig.SynfigStudio](https://github.com/flathub/org.synfig.SynfigStudio)
 * [x] [com.abisource.AbiWord](https://github.com/flathub/com.abisource.AbiWord)
 * [x] [com.github.gijsgoudzwaard.image-optimizer](https://github.com/flathub/com.github.gijsgoudzwaard.image-optimizer)
 * [x] [org.gnome.Gtranslator](https://github.com/flathub/org.gnome.Gtranslator)
 * [x] [ind.ie.Gnomit](https://github.com/flathub/ind.ie.Gnomit)
 * [x] [im.pidgin.Pidgin](https://github.com/flathub/im.pidgin.Pidgin) (https://github.com/flathub/im.pidgin.Pidgin/pull/4)
 * [x] [nl.hjdskes.gcolor3](https://github.com/flathub/nl.hjdskes.gcolor3)
 * [x] [com.github.artemanufrij.playmymusic](https://github.com/flathub/com.github.artemanufrij.playmymusic)
 * [x] [com.stepmania.StepMania](https://github.com/flathub/com.stepmania.StepMania)
 * [x] [org.freedesktop.Piper](https://github.com/flathub/org.freedesktop.Piper)
 * [x] [org.gahshomar.Gahshomar](https://github.com/flathub/org.gahshomar.Gahshomar)
 * [x] ~~[[com.github.danrabbit.harvey](https://github.com/flathub/com.github.danrabbit.harvey)~~[
 * [x] [org.gnome.Shotwell](https://github.com/flathub/org.gnome.Shotwell)
 * [x] [net.baseart.Glide](https://github.com/flathub/net.baseart.Glide)
 * [x] [org.gnome.Evolution](https://github.com/flathub/org.gnome.Evolution)
 * [x] [org.gnome.PasswordSafe](https://github.com/flathub/org.gnome.PasswordSafe)
 * [x] [org.gnome.SoundRecorder](https://github.com/flathub/org.gnome.SoundRecorder)
 * [x] [org.gnome.SwellFoop](https://github.com/flathub/org.gnome.SwellFoop)
 * [x] [org.cznic.Datovka](https://github.com/flathub/org.cznic.Datovka)
 * [x] [com.github.artemanufrij.regextester](https://github.com/flathub/com.github.artemanufrij.regextester)
 * [x] [org.gnome.IconPreview](https://github.com/flathub/org.gnome.IconPreview)
 * [x] [net.sourceforge.electrip.Electrip](https://github.com/flathub/net.sourceforge.electrip.Electrip)
 * [x] [io.gitlab.Goodvibes](https://github.com/flathub/io.gitlab.Goodvibes)
 * [x] [com.gitlab.bitseater.meteo](https://github.com/flathub/com.gitlab.bitseater.meteo)
 * [x] [com.github.maoschanz.DynamicWallpaperEditor](https://github.com/flathub/com.github.maoschanz.DynamicWallpaperEditor)
 * [x] [im.bernard.Nostalgia](https://github.com/flathub/im.bernard.Nostalgia)
 * [x] [com.notepadqq.Notepadqq](https://github.com/flathub/com.notepadqq.Notepadqq)
 * [x] [com.github.lainsce.timetable](https://github.com/flathub/com.github.lainsce.timetable)
 * [x] [com.github.PintaProject.Pinta](https://github.com/flathub/com.github.PintaProject.Pinta)
 * [ ] [org.freac.freac](https://github.com/flathub/org.freac.freac)
 * [x] [app.rednotebook.RedNotebook](https://github.com/flathub/app.rednotebook.RedNotebook)
 * [x] [nl.g4d.Girens](https://github.com/flathub/nl.g4d.Girens)
 * [x] [org.caione.GScope](https://github.com/flathub/org.caione.GScope)
 * [x] [net.danigm.timetrack](https://github.com/flathub/net.danigm.timetrack)
 * [x] [com.github.calo001.fondo](https://github.com/flathub/com.github.calo001.fondo)
 * [x] [com.github.muriloventuroso.givemelyrics](https://github.com/flathub/com.github.muriloventuroso.givemelyrics)
 * [x] [com.wings3d.WINGS](https://github.com/flathub/com.wings3d.WINGS)
 * [x] [org.gnome.OCRFeeder](https://github.com/flathub/org.gnome.OCRFeeder)
 * [x] [io.otsaloma.gaupol](https://github.com/flathub/io.otsaloma.gaupol)
 * [x] [org.gnome.PowerStats](https://github.com/flathub/org.gnome.PowerStats)
 * [x] [org.gnome.ColorViewer](https://github.com/flathub/org.gnome.ColorViewer)
 * [x] [net.mancubus.SLADE](https://github.com/flathub/net.mancubus.SLADE)
 * [x] [com.github.bcedu.valasimplehttpserver](https://github.com/flathub/com.github.bcedu.valasimplehttpserver)
 * [x] [com.github.calo001.luna](https://github.com/flathub/com.github.calo001.luna)
 * [x] [org.bluej.BlueJ](https://github.com/flathub/org.bluej.BlueJ)
 * [x] [com.jonathankang.Weibird](https://github.com/flathub/com.jonathankang.Weibird)
 * [x] [io.github.liberodark.OpenDrive](https://github.com/flathub/io.github.liberodark.OpenDrive)
 * [x] [org.gaphor.Gaphor](https://github.com/flathub/org.gaphor.Gaphor)
 * [x] [br.gov.cti.invesalius](https://github.com/flathub/br.gov.cti.invesalius)
 * [x] [com.xnview.XnSketch](https://github.com/flathub/com.xnview.XnSketch)
 * [x] [com.github.Cogitri.gxi](https://github.com/flathub/com.github.Cogitri.gxi)
 * [x] [com.xnview.XnConvert](https://github.com/flathub/com.xnview.XnConvert)
 * [x] [com.xnview.XnViewMP](https://github.com/flathub/com.xnview.XnViewMP)
 * [x] [com.xnview.XnRetro](https://github.com/flathub/com.xnview.XnRetro)
 * [x] [com.github.naaando.lyrics](https://github.com/flathub/com.github.naaando.lyrics)
 * [x] [com.github.maoschanz.drawing](https://github.com/flathub/com.github.maoschanz.drawing)
 * [ ] [org.gabmus.unifydmin](https://github.com/flathub/org.gabmus.unifydmin)
 * [x] [mx.pwmc.Svgvi](https://github.com/flathub/mx.pwmc.Svgvi)
 * [x] [com.kavilgroup.gestimator](https://github.com/flathub/com.kavilgroup.gestimator)
 * [x] [net.jami.Jami](https://github.com/flathub/net.jami.Jami)
 * [x] [org.gnome.LightsOff](https://github.com/flathub/org.gnome.LightsOff)
 * [x] [com.github.artemanufrij.playmyvideos](https://github.com/flathub/com.github.artemanufrij.playmyvideos)
 * [x] [org.gnome.Notes](https://github.com/flathub/org.gnome.Notes)
 * [x] [io.howl.Editor](https://github.com/flathub/io.howl.Editor)
 * [x] [org.gnome.Logs](https://github.com/flathub/org.gnome.Logs)
 * [x] [com.github.artemanufrij.graphui](https://github.com/flathub/com.github.artemanufrij.graphui)
 * [x] [org.gnome.Tali](https://github.com/flathub/org.gnome.Tali)
 * [x] [de.haeckerfelix.Remotely](https://github.com/flathub/de.haeckerfelix.Remotely)
 * [x] [ar.com.tuxguitar.TuxGuitar](https://github.com/flathub/ar.com.tuxguitar.TuxGuitar)
 * [x] [org.gnome.seahorse.Application](https://github.com/flathub/org.gnome.seahorse.Application)
 * [x] [fr.fgrabenstaetter.DigitalAssets](https://github.com/flathub/fr.fgrabenstaetter.DigitalAssets)
 * [x] [org.gnome.Mines](https://github.com/flathub/org.gnome.Mines)
 * [x] [com.github.lachhebo.Gabtag](https://github.com/flathub/com.github.lachhebo.Gabtag)
 * [x] [com.github.johnfactotum.Foliate](https://github.com/flathub/com.github.johnfactotum.Foliate)
 * [ ] [com.github.IsmaelMartinez.teams_for_linux](https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux)
 * [x] [net.lutris.Lutris](https://github.com/flathub/net.lutris.Lutris)
 * [x] [org.gnome.Sudoku](https://github.com/flathub/org.gnome.Sudoku)

**Comment by Erick555** [comment]
@hadess isn't flatpak 1.4 needed too?

**Comment by hadess** [comment]
> @hadess isn't flatpak 1.4 needed too?

I don't think so, and my research doesn't show it would be needed either. Would be useful to say why you think this particular version is necessary.

**Comment by Erick555** [comment]
Because this is what they claim in release notes: https://github.com/flatpak/flatpak/releases/tag/1.3.0 . Before I saw this ticket everyone was talking about flatpak 1.4 need.

**Comment by hadess** [comment]
> Because there is info about added dconf support in release notes: https://github.com/flatpak/flatpak/releases/tag/1.3.0 . Before I saw this ticket everyone was talking about flatpak 1.4 need.

It's useful but not strictly necessary.

**Comment by TingPing** [comment]
I think gradual adoption is fine as just jumping over now is a bad UX:

- Without `flatpak` 1.4 suddenly users lose settings
- Without `xdg-desktop-portal` 1.1 host integration will break on Wayland

Also fdo 18.08 doesn't have glib 2.60 (though this could be backported).

**Comment by TingPing** [comment]
Also add every KDE app to your list since the runtime pulls it in: https://github.com/KDE/flatpak-kde-runtime/blob/qt5.12lts/org.kde.Sdk.json#L55

**Comment by hadess** [comment]
> Also add every KDE app to your list since the runtime pulls it in: https://github.com/KDE/flatpak-kde-runtime/blob/qt5.12lts/org.kde.Sdk.json#L55

That's in the runtime, not in individual apps.

**Comment by Erick555** [comment]
> That's in the runtime, not in individual apps.

AFAIK apps are inheriting those from runtime.

**Comment by Erick555** [comment]
> That's in the runtime, not in individual apps.

AFAIK apps are inheriting those from runtime so it have to be changed in runtime however as KDE is based on fdo 18.08 which doesn't have newer glib it can't be done atm.

**Comment by hadess** [comment]
> AFAIK apps are inheriting those from runtime so it have to be changed in runtime however as KDE is based on fdo 18.08 which doesn't have newer glib it can't be done atm.

Added KDE

**Comment by TingPing** [comment]
So the first pass of applications that its best to remove this from is probably GTK2 and Qt ones.

If the app:

- Doesn't use DConf for its own settings storage
- Doesn't support Wayland

It then means there is no regression removing it.

**Comment by FakeShemp** [comment]
`com.stepmania.StepMania` updated.

**Comment by grulja** [comment]
You can mark KDE runtime as done. See https://github.com/KDE/flatpak-kde-runtime/commit/f41edbbb756418d9ea3cc5065e27073aeaeaadbb

**Comment by x80486** [comment]
I'm sure I don't fully understand this `DConf` business, but how is `io.github.liberodark.OpenDrive` impacted by this? What is it what needs to be done to "fix" it? My knowledge is constrained to [this](http://docs.flatpak.org/en/latest/sandbox-permissions.html#dconf-access) guide.

**Comment by bochecha** [comment]
ch.x29a.playitslowly is done (flathub/ch.x29a.playitslowly#2)

**Comment by dgcampea** [comment]
These apps have already been updated.

https://github.com/flathub/io.github.Pithos
[Archived] https://github.com/flathub/io.github.GnomeMpv
https://github.com/flathub/org.audacityteam.Audacity
https://github.com/flathub/org.mypaint.MyPaint
https://github.com/flathub/org.gnome.Polari
https://github.com/flathub/com.github.wwmm.pulseeffects
https://github.com/flathub/org.gnome.Builder
https://github.com/flathub/de.manuel_kehl.go-for-it
https://github.com/flathub/org.gnome.Maps
https://github.com/flathub/com.github.birros.WebArchives
[Archived] https://github.com/flathub/cx.ring.Ring
https://github.com/flathub/org.gnome.Gnote
https://github.com/flathub/com.google.AndroidStudio
https://github.com/flathub/io.github.jliljebl.Flowblade
[Archived] https://github.com/flathub/com.github.bitseater.weather
https://github.com/flathub/org.mozilla.Thunderbird
https://github.com/flathub/io.github.janbar.noson
https://github.com/flathub/com.github.muriloventuroso.easyssh
https://github.com/flathub/com.axosoft.GitKraken
https://github.com/flathub/org.synfig.SynfigStudio
https://github.com/flathub/net.mancubus.SLADE
https://github.com/flathub/com.github.bcedu.valasimplehttpserver
[Archived] https://github.com/flathub/com.github.Cogitri.gxi
https://github.com/flathub/com.github.naaando.lyrics
https://github.com/flathub/mx.pwmc.Svgvi
https://github.com/flathub/net.jami.Jami
https://github.com/flathub/com.github.johnfactotum.Foliate
https://github.com/flathub/net.lutris.Lutris

https://github.com/flathub/org.remmina.Remmina

**Comment by dgcampea** [comment]
https://github.com/flathub/org.filezillaproject.Filezilla/pull/44

**Comment by dgcampea** [comment]
https://github.com/flathub/org.libreoffice.LibreOffice/pull/110

**Comment by dgcampea** [comment]
https://github.com/flathub/app.rednotebook.RedNotebook/pull/4

**Comment by FakeShemp** [comment]
com.slack.Slack should be updated

**Comment by A6GibKm** [comment]
org.gnome.Calendar and org.gnome.PasswordSafe were updated some time ago.

**Comment by darkdragon-001** [comment]
com.github.PintaProject.Pinta should be updated

**Comment by bbhtt** [comment]
I've updated the checklist in the OP. These are the ones remaining, if anyone wants to help. I'll try to get to some of them in the coming weeks.

* [ ] https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux
* [ ] https://github.com/flathub/org.gabmus.unifydmin (Should be made EOL as per author)
* [ ] https://github.com/flathub/org.bluej.BlueJ
* [ ] https://github.com/flathub/com.wings3d.WINGS
* [ ] https://github.com/flathub/nl.g4d.Girens
* [ ] https://github.com/flathub/org.freac.freac
* [ ] https://github.com/flathub/com.notepadqq.Notepadqq
* [ ] https://github.com/flathub/org.gnome.Gtranslator
* [ ] https://github.com/flathub/org.laptop.TurtleArtActivity
* [ ] https://github.com/flathub/com.github.marktext.marktext
* [ ] https://github.com/flathub/org.gnome.Boxes
* [ ] https://github.com/flathub/com.lettier.movie-monad (Should probably be made EOL)
* [ ] https://github.com/flathub/org.gabmus.hydrapaper
* [ ] https://github.com/flathub/ca._0ldsk00l.Nestopia
* [ ] https://github.com/flathub/ca.desrt.dconf-editor (Seems necessary?)

**Comment by bbhtt** [comment]
All are done here, the combination will be blocked by the linter shortly.

**Comment by bbhtt** [comment]
> The combination will be blocked by the linter shortly.

See https://github.com/flathub-infra/flatpak-builder-lint/pull/429
