### ISSUE TITLE
Tracker for applications missing OARS information

### ISSUE THREAD

**Issue by andrunko** [flathub/flathub#1081]
The following applications seem to be missing OARS information:

- [ ] https://github.com/flathub/com.chez.GrafX2
- [ ] https://github.com/flathub/com.github.libresprite.LibreSprite
- [ ] https://github.com/flathub/com.lettier.movie-monad
- [ ] https://github.com/flathub/com.remarkable.reMarkable
- [ ] https://github.com/flathub/com.visualstudio.code.oss
- [ ] https://github.com/flathub/fr.free.Homebank
- [ ] https://github.com/flathub/io.ark.Desktop
- [ ] https://github.com/flathub/io.github.cloose.CuteMarkEd
- [ ] https://github.com/flathub/io.github.guillaumechereau.Goxel
- [ ] https://github.com/flathub/io.github.wereturtle.ghostwriter
- [ ] https://github.com/flathub/io.gitlab.osslugaru.Lugaru
- [ ] https://github.com/flathub/io.howl.Editor
- [ ] https://github.com/flathub/net.olofson.KoboDeluxe
- [ ] https://github.com/flathub/net.sourceforge.btanks
- [ ] https://github.com/flathub/net.sourceforge.mars-game
- [ ] https://github.com/flathub/org.freecol.FreeCol
- [ ] https://github.com/flathub/org.freedesktop.GstDebugViewer
- [ ] https://github.com/flathub/org.kde.dolphin
- [ ] https://github.com/flathub/org.kde.kalzium
- [ ] https://github.com/flathub/org.kde.kapman
- [ ] https://github.com/flathub/org.kde.katomic
- [ ] https://github.com/flathub/org.kde.kblocks
- [ ] https://github.com/flathub/org.kde.kbruch
- [ ] https://github.com/flathub/org.kde.kdiamond
- [ ] https://github.com/flathub/org.kde.kgoldrunner
- [ ] https://github.com/flathub/org.kde.khangman
- [ ] https://github.com/flathub/org.kde.kigo
- [ ] https://github.com/flathub/org.kde.killbots
- [ ] https://github.com/flathub/org.kde.kjumpingcube
- [ ] https://github.com/flathub/org.mapeditor.Tiled
- [ ] https://github.com/flathub/org.seul.pingus
- [ ] https://github.com/flathub/org.sparkleshare.SparkleShare
- [ ] https://github.com/flathub/org.tuxfamily.XMoto
- [ ] https://github.com/flathub/org.xiphos.Xiphos

**Comment by AsciiWolf** [comment]
`org.gnome.chess` is deprecated, it was renamed to `org.gnome.Chess`.

**Comment by bilelmoussaoui** [comment]
*.BaseApp should be removed from this list.

**Comment by FakeShemp** [comment]
com.krillbite.ThePlan is end-of-life. I'm not sure why it still shows up on flathub.

**Comment by TingPing** [comment]
> com.krillbite.ThePlan is end-of-life. I'm not sure why it still shows up on flathub.

It is forever in the repo, otherwise I believe existing installs wouldn't be happy.

**Comment by bochecha** [comment]
Blender is done: https://github.com/flathub/org.blender.Blender/pull/30

**Comment by brendanlong** [comment]
I'm not sure if this is the right place to ask, but I'm one of the maintainers of FeedReader, which [already has this info](https://github.com/jangernert/FeedReader/blob/master/data/org.gnome.FeedReader.appdata.xml.in#L67). My question is if there's any guidance about how to handle browser-like apps. FeedReader itself has no advertising or adult content, but you could easily subscribe to gambling, porn and ad-heavy RSS feeds. I'm asking because I can find a generator but I can't actually find a spec for what the OARS options are.

Also, I went through the generator and it seems strange that it asked me about a lot of things but _didn't_ ask about adult content. It seems like a weird thing not to include in content rating since it's probably the #1 thing most parents want.

**Comment by barthalion** [comment]
I think that assumption is that you have no control over external content that can be loaded by your application, so technically it does not "ship" ads or gambling.

**Comment by wjt** [comment]
I agree that some special handling for browser-esque apps is needed, and that the generator should ask authors of non-game applications some (if not all) of the content questions. Tickets opened about both.

**Comment by gjanssens** [comment]
GnuCash has added OARS information upstream for their 3.7 release:
https://github.com/Gnucash/gnucash/commit/ce638f3084abc26d45b3bf0ba7417c31346e5689

This release has been pushed earlier today on flathub.

**Comment by bochecha** [comment]
ch.x29a.playitslowly is done (https://github.com/flathub/ch.x29a.playitslowly/pull/2)

**Comment by hfiguiere** [comment]
Darktable has OARS information in (can't check it in the list)

**Comment by hfiguiere** [comment]
Wesnoth has OARS info too.

**Comment by hfiguiere** [comment]
org.musesequencer.Muse3 has OARS too.

**Comment by hfiguiere** [comment]
org.hydrogenmusic.Hydrogen has OARS.

**Comment by SISheogorath** [comment]
As I just checked: Darktable has a content rating already.

**Comment by wjt** [comment]
Here's a script to check which apps are outstanding: https://gist.github.com/wjt/9fc2230bdb4705413d5fa59b276d135a

Here is the complete list according to that script:

- [ ] https://github.com/flathub/com.chez.GrafX2
- [ ] https://github.com/flathub/com.github.libresprite.LibreSprite
- [ ] https://github.com/flathub/com.lettier.movie-monad
- [ ] https://github.com/flathub/com.remarkable.reMarkable
- [ ] https://github.com/flathub/com.visualstudio.code.oss
- [ ] https://github.com/flathub/fr.free.Homebank
- [ ] https://github.com/flathub/io.ark.Desktop
- [ ] https://github.com/flathub/io.github.cloose.CuteMarkEd
- [ ] https://github.com/flathub/io.github.guillaumechereau.Goxel
- [ ] https://github.com/flathub/io.github.wereturtle.ghostwriter
- [ ] https://github.com/flathub/io.gitlab.osslugaru.Lugaru
- [ ] https://github.com/flathub/io.howl.Editor
- [ ] https://github.com/flathub/net.olofson.KoboDeluxe
- [ ] https://github.com/flathub/net.sourceforge.btanks
- [ ] https://github.com/flathub/net.sourceforge.mars-game
- [ ] https://github.com/flathub/org.freecol.FreeCol
- [ ] https://github.com/flathub/org.freedesktop.GstDebugViewer
- [ ] https://github.com/flathub/org.kde.dolphin
- [ ] https://github.com/flathub/org.kde.kalzium
- [ ] https://github.com/flathub/org.kde.kapman
- [ ] https://github.com/flathub/org.kde.katomic
- [ ] https://github.com/flathub/org.kde.kblocks
- [ ] https://github.com/flathub/org.kde.kbruch
- [ ] https://github.com/flathub/org.kde.kdiamond
- [ ] https://github.com/flathub/org.kde.kgoldrunner
- [ ] https://github.com/flathub/org.kde.khangman
- [ ] https://github.com/flathub/org.kde.kigo
- [ ] https://github.com/flathub/org.kde.killbots
- [ ] https://github.com/flathub/org.kde.kjumpingcube
- [ ] https://github.com/flathub/org.mapeditor.Tiled
- [ ] https://github.com/flathub/org.seul.pingus
- [ ] https://github.com/flathub/org.sparkleshare.SparkleShare
- [ ] https://github.com/flathub/org.tuxfamily.XMoto
- [ ] https://github.com/flathub/org.xiphos.Xiphos

Perhaps @andrunko or a Flathub admin could update the issue description accordingly?

Or, since this is now enforced by the Flathub build infrastructure for app updates, perhaps instead we could file these 34 issues and resolve this?

**Comment by bilelmoussaoui** [comment]
@wjt I have updated the issue list, thanks! I also noticed that a lot of these apps have a common pattern, they are shipping a flathub.json with a `"skip-appstream-check": true` we should probably open an issue on all of these to get a fixed/updated appdata for these apps as well

**Comment by razzeee** [comment]
I've just ran that script from @bilelmoussaoui 

And it only returned these

- [ ] https://github.com/flathub/com.lettier.movie-monad
- [ ] https://github.com/flathub/io.ark.Desktop
- [ ] https://github.com/flathub/io.gitlab.osslugaru.Lugaru
- [ ] https://github.com/flathub/org.sparkleshare.SparkleShare

**Comment by hfiguiere** [comment]
if memory server SparkleShare has issues with the dotnet/mono runtime.

**Comment by hfiguiere** [comment]
Movie monad use Haskell (ghc) which mean that the knowledge gap is gigantic.

**Comment by hfiguiere** [comment]
For Lugaru the OARS is 1.0. Is that the problem?

**Comment by razzeee** [comment]
Thx, lugaru now shows OARS fine in gnome software

**Comment by hfiguiere** [comment]
seems that gnome-software doesn't like oars-1.0

**Comment by bbhtt** [comment]
This is caught by validation. Let's close this.

https://github.com/flathub/flathub/issues/1081#issuecomment-1596164876 everything unchecked here is not being maintained anymore.

skip-appstream-check no longer exists for any actual applications.
