### ISSUE TITLE
Tracker for applications using --socket=x11 and --socket=wayland

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#1452]
In version 1.0, Flatpak gained the ability to provide access to the X11 socket on the condition that the windowing system used was X11, and not Wayland. Those applications currently have access to both Wayland and X11 sockets when running on Wayland. Ideally, they would instead use the `fallback-x11` permission (`--socket=fallback-x11` in the `finish-args`):

- [ ] app.rednotebook.RedNotebook
- [ ] ar.com.tuxguitar.TuxGuitar
- [ ] at.priv.toastfreeware.ConfClerk
- [ ] ca._0ldsk00l.Nestopia
- [ ] ca.parallel_launcher.ParallelLauncher
- [ ] cc.retroshare.retroshare-gui
- [ ] chat.quadrix.Quadrix
- [ ] chat.rocket.RocketChat
- [ ] chat.schildi.desktop
- [ ] ch.openboard.OpenBoard
- [ ] com.abagames.rRootage
- [ ] com.adamcake.Bolt
- [ ] com.avocode.Avocode
- [ ] com.bitwarden.desktop
- [ ] com.bixense.PasswordCalculator
- [ ] com.bladecoder.adventure-editor
- [ ] com.brave.Browser
- [ ] com.chez.GrafX2
- [ ] com.dec05eba.gpu_screen_recorder
- [ ] com.freerdp.FreeRDP
- [ ] com.fribbledom.telephant
- [ ] com.getmailspring.Mailspring
- [ ] com.github._4lex4.ScanTailor-Advanced
- [ ] com.github.artemanufrij.graphui
- [ ] com.github.artemanufrij.playmymusic
- [ ] com.github.artemanufrij.regextester
- [ ] com.github.babluboy.bookworm
- [ ] com.github.Bleuzen.FFaudioConverter
- [ ] com.github.calo001.fondo
- [ ] com.github.coslyk.MoonPlayer
- [ ] com.github.dahenson.agenda
- [ ] com.github.donadigo.appeditor
- [ ] com.github.gijsgoudzwaard.image-optimizer
- [ ] com.github.gyunaev.spivak
- [ ] com.github.hluk.copyq
- [ ] com.github.IsmaelMartinez.teams_for_linux
- [ ] com.github.maoschanz.DynamicWallpaperEditor
- [ ] com.github.marktext.marktext
- [ ] com.github.Matoking.protontricks
- [ ] com.github.mtkennerly.ludusavi
- [ ] com.github.muriloventuroso.easyssh
- [ ] com.github.naaando.lyrics
- [ ] com.github.nrittsti.NTag
- [ ] com.github.philip_scott.notes-up
- [ ] com.github.philip_scott.spice-up
- [ ] com.github.quaternion
- [ ] com.github.Qv2ray
- [ ] com.github.raibtoffoletto.litteris
- [ ] com.github.robertsanseries.ciano
- [ ] com.github.wwmm.pulseeffects
- [ ] com.gitlab.librebob.Athenaeum
- [ ] com.google.Chrome
- [ ] com.google.ChromeDev
- [ ] com.heroicgameslauncher.hgl
- [ ] com.jetbrains.CLion
- [ ] com.jetbrains.DataGrip
- [ ] com.jetbrains.IntelliJ-IDEA-Community
- [ ] com.jetbrains.IntelliJ-IDEA-Ultimate
- [ ] com.jetbrains.WebStorm
- [ ] com.katawa_shoujo.KatawaShoujo
- [ ] com.lettier.movie-monad
- [ ] com.locomalito.abbayedesmorts
- [ ] com.logseq.Logseq
- [ ] com.lunarclient.LunarClient
- [ ] com.mastermindzh.tidal-hifi
- [ ] com.mattermost.Desktop
- [ ] com.microsoft.Edge
- [ ] com.microsoft.EdgeDev
- [ ] com.milesalan.mepo
- [ ] com.modrinth.ModrinthApp
- [ ] com.mousepawmedia.omission
- [ ] com.notesnook.Notesnook
- [ ] com.obsproject.Studio
- [ ] com.opera.Opera
- [ ] com.play0ad.zeroad
- [ ] com.pot_app.pot
- [ ] com.prusa3d.PrusaSlicer
- [ ] com.revolutionarygamesstudio.ThriveLauncher
- [ ] com.shatteredpixel.shatteredpixeldungeon
- [ ] com.slugchess.SlugChess
- [ ] com.sublimetext.three
- [ ] com.supermodel3.Supermodel
- [ ] com.syntevo.SmartGit
- [ ] com.syntevo.SmartSynchronize
- [ ] com.ticktick.TickTick
- [ ] com.tutanota.Tutanota
- [ ] com.ultimaker.cura
- [ ] com.uploadedlobster.peek
- [ ] com.usebottles.bottles
- [ ] com.valvesoftware.Steam
- [ ] com.viber.Viber
- [ ] com.visualstudio.code-oss
- [ ] com.vivaldi.Vivaldi
- [ ] com.wire.WireDesktop
- [ ] com.wiz.Note
- [ ] com.xnview.XnViewMP
- [ ] de.akaflieg_freiburg.cavok.add_hours_and_minutes
- [ ] de.flinkebits.AvaEmailArchivar
- [ ] de.klayout.KLayout
- [ ] de.unifreiburg.ellipticcurve
- [ ] dev.storyapps.starc
- [ ] de.willuhn.Jameica
- [ ] edu.stanford.Almond
- [ ] eu.ototu.Quteqoin
- [ ] eu.planete_kraus.Tarot
- [ ] fr.fgrabenstaetter.DigitalAssets
- [ ] ga.rpmtw.rpmlauncher
- [ ] im.kaidan.kaidan
- [ ] im.nheko.Nheko
- [ ] im.riot.Riot
- [ ] im.srain.Srain
- [ ] in.cinny.Cinny
- [ ] info.bibletime.BibleTime
- [ ] in.srev.guiscrcpy
- [ ] io.gdevelop.ide
- [ ] io.github.aggalex.Wineglass
- [ ] io.github.cges30901.hmtimer
- [ ] io.github.cloose.CuteMarkEd
- [ ] io.github.dbchoco.Salawat
- [ ] io.github.dweymouth.supersonic
- [ ] io.github.gerryferdinandus.bittorrent-tracker-editor
- [ ] io.github.guillaumechereau.Goxel
- [ ] io.github.hermitdemschoenenleben.linien
- [ ] io.github.ja2_stracciatella.JA2-Stracciatella
- [ ] io.github.jacalz.rymdport
- [ ] io.github.janbar.noson
- [ ] io.github.maddecoder.Classic-RBDOOM-3-BFG
- [ ] io.github.mki1967.mki3dgame
- [ ] io.github.mmstick.FontFinder
- [ ] io.github.pd_l2ork.Pd_L2Ork
- [ ] io.github.qnapi
- [ ] io.github.rinigus.OSMScoutServer
- [ ] io.github.rinigus.PureMaps
- [ ] io.github.sharkwouter.Minigalaxy
- [ ] io.github.slgobinath.SafeEyes
- [ ] io.github.technic.e2designer
- [ ] io.github.trigg.discover_overlay
- [ ] io.github.ungoogled_software.ungoogled_chromium
- [ ] io.gitlab.o20.word
- [ ] io.gitlab.Turtlico
- [ ] io.howl.Editor
- [ ] io.itch.doctorm64.skippybot
- [ ] io.itch.itch
- [ ] io.jamulus.Jamulus
- [ ] io.kinvolk.Headlamp
- [ ] io.lbry.lbry-app
- [ ] io.liri.Calculator
- [ ] io.liri.Text
- [ ] io.mpv.Mpv
- [ ] io.otsaloma.gaupol
- [ ] io.otsaloma.nfoview
- [ ] io.qt.QtCreator
- [ ] io.typora.Typora
- [ ] jp.yvt.OpenSpades
- [ ] net.bartkessels.getit
- [ ] net.codeindustry.MasterPDFEditor
- [ ] net.davidotek.pupgui2
- [ ] net.devolutions.RDM
- [ ] net.displaycal.DisplayCAL
- [ ] net.hovancik.Stretchly
- [ ] net.lutris.Lutris
- [ ] net.mediaarea.AVIMetaEdit
- [ ] net.mediaarea.BWFMetaEdit
- [ ] net.mediaarea.DVAnalyzer
- [ ] net.mediaarea.MediaConch
- [ ] net.mediaarea.MediaInfo
- [ ] net.mediaarea.MOVMetaEdit
- [ ] net.mediaarea.QCTools
- [ ] net.meshlab.MeshLab
- [ ] net.mullvad.MullvadBrowser
- [ ] net.oz9aec.Gpredict
- [ ] net.pioneerspacesim.Pioneer
- [ ] net.retrodeck.retrodeck
- [ ] net.rpdev.OpenTodoList
- [ ] net.sf.nootka
- [ ] net.sourceforge.dmidiplayer
- [ ] net.sourceforge.kmetronome
- [ ] net.sourceforge.kmidimon
- [ ] net.sourceforge.Lifeograph
- [ ] net.studio08.xbplay
- [ ] net.unvanquished.Unvanquished
- [ ] net.wz2100.wz2100
- [ ] nl.openoffice.bluefish
- [ ] nz.mega.MEGAsync
- [ ] one.ablaze.floorp
- [ ] org.b3log.siyuan
- [ ] org.bitbucket.mystery_keeper.VapourSynthEditor
- [ ] org.bunkus.mkvtoolnix-gui
- [ ] org.chromium.Chromium
- [ ] org.claws_mail.Claws-Mail
- [ ] org.codeblocks.codeblocks
- [ ] org.dust3d.dust3d
- [ ] org.eu.encom.spectral
- [ ] org.fdroid.Repomaker
- [ ] org.ferdium.Ferdium
- [ ] org.flameshot.Flameshot
- [ ] org.free_astro.siril
- [ ] org.freedesktop.adriconf
- [ ] org.freedesktop.Piper
- [ ] org.freedesktop.Tuhi
- [ ] org.freeplane.App
- [ ] org.frescobaldi.Frescobaldi
- [ ] org.fritzing.Fritzing
- [ ] org.gabmus.unifydmin
- [ ] org.geeqie.Geeqie
- [ ] org.geogebra.GeoGebra
- [ ] org.getmonero.Monero
- [ ] org.gnome.Eolie
- [ ] org.gnome.Games
- [ ] org.gnome.Genius
- [ ] org.gnome.Keysign
- [ ] org.gnome.OCRFeeder
- [ ] org.gnome.OfficeRunner
- [ ] org.gnome.Tau
- [ ] org.hedgewars.Hedgewars
- [ ] org.homelinuxserver.vance.biblereader
- [ ] org.inkscape.Inkscape
- [ ] org.jaspstats.JASP
- [ ] org.karapulse.Karapulse
- [ ] org.kde.kamoso
- [ ] org.kde.kig
- [ ] org.kde.ktouch
- [ ] org.kde.kxstitch
- [ ] org.kde.marble
- [ ] org.kde.skrooge
- [ ] org.keepassxc.KeePassXC
- [ ] org.KekikAkademi.BTKSorgu
- [ ] org.kiwix.desktop
- [ ] org.librepcb.LibrePCB
- [ ] org.mamedev.MAME
- [ ] org.mobsya.ThymioSuite
- [ ] org.mozilla.Thunderbird
- [ ] org.msweet.htmldoc
- [ ] org.munadi.Munadi
- [ ] org.musicbrainz.Picard
- [ ] org.octave.Octave
- [ ] org.olivevideoeditor.Olive
- [ ] org.onlyoffice.desktopeditors
- [ ] org.openchemistry.Avogadro2
- [ ] org.openkj.OpenKJ
- [ ] org.openmsx.openMSX
- [ ] org.pjbroad.EternallandsClient
- [ ] org.polymc.PolyMC
- [ ] org.ppsspp.PPSSPP
- [ ] org.prismlauncher.PrismLauncher
- [ ] org.pyzo.pyzo
- [ ] org.qgis.qgis
- [ ] org.quetoo.Quetoo
- [ ] org.raceintospace.Raceintospace
- [ ] org.robocode.Robocode
- [ ] org.sauerbraten.Sauerbraten
- [ ] org.scummvm.ScummVM
- [ ] org.shadowsocks.qt5client
- [ ] org.signal.Signal
- [ ] org.sparkleshare.SparkleShare
- [ ] org.speedcrunch.SpeedCrunch
- [ ] org.synfig.SynfigStudio
- [ ] org.tropy.Tropy
- [ ] org.tug.texworks
- [ ] org.tuxemon.Tuxemon
- [ ] org.tuxpaint.Tuxpaint
- [ ] org.vinegarhq.Vinegar
- [ ] org.vranki.spectral
- [ ] org.winehq.Wine
- [ ] org.zim_wiki.Zim
- [ ] org.zrythm.Zrythm
- [ ] org.zulip.Zulip
- [ ] page.codeberg.JakobDev.jdMinecraftLauncher
- [ ] page.codeberg.lazyt.ubpm
- [ ] party.supertux.supertuxparty
- [ ] ru.linux_gaming.PortProton
- [ ] sa.sy.bluerecorder
- [ ] sh.cider.Cider
- [ ] sh.fhs.KatawaShoujoReEngineered
- [ ] space.fips.Fips
- [ ] studio.kx.carla
- [ ] tv.plex.PlexHTPC
- [ ] ua.org.brezblock.q4wine
- [ ] uk.jnthn.backgammony
- [ ] uk.me.doof.Lander
- [ ] us.zoom.Zoom
- [ ] website.i2pd.i2pd
- [ ] xyz.hyperplay.HyperPlay
- [ ] xyz.splashmapper.Splash
- [ ] xyz.stuerz.BilligSweeper

~The list was generated with the [list-all-x11-repos.sh script](https://github.com/hadess/filter-flathub-repos).~ Source. https://github.com/flathub-infra/flatpak-builder-lint/issues/414#issuecomment-2185669890

**Comment by nedrichards** [comment]
@tsdgeos @grulja would KDE prefer "wayland by default" or "difficult for normal users to use anything by xwayland" (the current state)? Which is the implication of this change. I know historically there had been some concerns with some of the Qt wayland stuff wrt flatpak so wouldn't want to push extra work if there's baking still needed.

**Comment by grulja** [comment]
Using `--socket=fallback-x11` will not work in cases when applications themself don't want to use Qt wayland platform plugin and they want to use xcb (X11) instead, even on Wayland. In that case Flatpak will still expect Wayland to be used, while apps would be trying to load xcb plugin and fail because of missing x11 socket. This might be case for video editors or vlc, which have some issues on Wayland or even Telegram.

**Comment by hadess** [comment]
> Using `--socket=fallback-x11` will not work in cases when applications themself don't want to use Qt wayland platform plugin and they want to use xcb (X11) instead, even on Wayland. In that case Flatpak will still expect Wayland to be used, while apps would be trying to load xcb plugin and fail because of missing x11 socket. This might be case for video editors or vlc, which have some issues on Wayland or even Telegram.

I've added a link to the script that generated this list. Note that all the applications listed claimed to want _both_ the X11 and Wayland sockets. I think that Qt apps that want to use X11 should not be requesting access to the Wayland socket.

**Comment by eszlari** [comment]
>  I think that Qt apps that want to use X11 should not be requesting access to the Wayland socket.

Does it make a big difference for security?

I prefer
```
--socket=wayland
--env=QT_QPA_PLATFORM=xcb
```
to document to the reader, that `--socket=wayland` was not simply forgotten, but the app doesn't support it.

Maybe
```
--nosocket=wayland
--nosocket=fallback-x11
```
conveys the same info, and provides an easy update path when the app is ready for wayland.

**Comment by hadess** [comment]
> Does it make a big difference for security?

It does make a difference for security. Whether it's big or not is not really the point though.

**Comment by TingPing** [comment]
Maybe we could just start the mass change ignoring apps on the KDE runtime for now.

**Comment by ilya-fedin** [comment]
> This might be case for video editors or vlc, which have some issues on Wayland or even Telegram.

I believe that https://github.com/flathub/org.telegram.desktop/issues/133 is not a tdesktop-specific issue, but a Qt/Mutter issue (https://bugreports.qt.io/browse/QTBUG-68622, https://gitlab.gnome.org/GNOME/mutter/issues/199) that has been fixed a long time ago, but Ubuntu 18.04 still offers a bugged mutter version. I believe that other Qt applications in flatpak doesn't have such issue tickets just because they're not so popular. And that's why I believe that [qtbase-use-wayland-on-gnome.patch](https://github.com/KDE/flatpak-kde-runtime/blob/qt5.14/patch/qtbase-use-wayland-on-gnome.patch) should be reverted.

(or maybe someone can raise this information to Canonical so that they can patch their mutter and even tdesktop can start defaulting to Wayland?)

**Comment by grulja** [comment]
> > This might be case for video editors or vlc, which have some issues on Wayland or even Telegram.
> 
> I believe that [flathub/org.telegram.desktop#133](https://github.com/flathub/org.telegram.desktop/issues/133) is not a tdesktop-specific issue, but a Qt/Mutter issue (https://bugreports.qt.io/browse/QTBUG-68622, https://gitlab.gnome.org/GNOME/mutter/issues/199) that has been fixed a long time ago, but Ubuntu 18.04 still offers a bugged mutter version. I believe that other Qt applications in flatpak doesn't have such issue tickets just because they're not so popular. And that's why I believe that [qtbase-use-wayland-on-gnome.patch](https://github.com/KDE/flatpak-kde-runtime/blob/qt5.14/patch/qtbase-use-wayland-on-gnome.patch) should be reverted.
> 
> (or maybe someone can raise this information to Canonical so that they can patch their mutter and even tdesktop can start defaulting to Wayland?)

We default to Wayland with Qt since Fedora 31 and while there were some issues at the beginning, they are now gone and running Qt apps natively on Wayland on Gnome is no longer a problem.

**Comment by ilya-fedin** [comment]
> We default to Wayland with Qt since Fedora 31

I don't know which mutter version Fedora 31 have, Ubuntu 18.04 ships [3.28.1](https://packages.ubuntu.com/bionic/mutter), which is old enough to have problems

According to the gnome gitlab, flickering issue was fixed [only in 3.31.92](https://gitlab.gnome.org/GNOME/mutter/-/commit/252e64a0eae61735a912d41817c6e6f24824146b):
![image](https://user-images.githubusercontent.com/17829319/87278467-0f7a3700-c4d4-11ea-9d9f-77660d6db863.png)

**Comment by grulja** [comment]
I believe Fedora 31 has GNOME 3.32 and newer. Still I'm not convinced that this argument is strong enough to limit everyone and let them stay on xwayland just because one distribution. If you submit a patch which will check Ubuntu version and avoids using Wayland there, I can push it to the runtime, but I'm not in favor of removing it.

**Comment by grulja** [comment]
> > We default to Wayland with Qt since Fedora 31
> 
> I don't know which mutter version Fedora 31 have, but Ubuntu 18.04 ships [3.28.1](https://packages.ubuntu.com/bionic/mutter), which is old enough to have problems
> 
> According to the gnome gitlab, flickering issue was fixed [only in 3.31.92](https://gitlab.gnome.org/GNOME/mutter/-/commit/252e64a0eae61735a912d41817c6e6f24824146b):
> ![image](https://user-images.githubusercontent.com/17829319/87278467-0f7a3700-c4d4-11ea-9d9f-77660d6db863.png)

I believe Fedora 31 has GNOME 3.32 and newer. Still I'm not convinced that this argument is strong enough to limit everyone and let them stay on xwayland just because one distribution. If you submit a patch which will check Ubuntu version and avoids using Wayland there, I can push it to the runtime, but I'm not in favor of removing it.

**Comment by nanonyme** [comment]
Note that for some apps (at least com.valvesoftware.Steam) moving away from --socket=x11 is undesirable. It should possibly be excluded from this list.

**Comment by bbhtt** [comment]
This is blocked by the linter now https://github.com/flathub-infra/flatpak-builder-lint/pull/424

I will update the OP with the list we generated for linter https://github.com/flathub-infra/flatpak-builder-lint/issues/414#issuecomment-2185669890

**Comment by mtkennerly** [comment]
For `com.github.mtkennerly.ludusavi`:

It was originally using `--socket=fallback-x11` + `--socket=wayland`, but I got a bug report (https://github.com/mtkennerly/ludusavi/issues/290) where Ludusavi wasn't able to invoke zenity and/or kdialog successfully. I was able to fix it by switching to `--socket=x11` + `--socket=wayland` (https://github.com/flathub/com.github.mtkennerly.ludusavi/pull/36).

I'm open to another solution, but `--socket=fallback-x11` vs `--socket=x11` did make a material difference in this case.

**Comment by nanonyme** [comment]
Sounds truly odd why zenity would not work with Wayland alone to me.

**Comment by dec05eba** [comment]
Hmm, at first I replaced the socket=x11 with socket=fallback-x11 and it works fine but I realized that I will need x11 on wayland too later on (because of wayland protocol limitations) so I tried to add it back: https://github.com/flathub/com.dec05eba.gpu_screen_recorder/pull/135 but it seems like it doesn't allow x11 connection (on x11) anymore, even though the program is in the exceptions.
It was in this commit that I had previously replaced socket=x11 with socket=fallback-x11: https://github.com/flathub/com.dec05eba.gpu_screen_recorder/commit/8587cbfe7dab01153adb55892e5ee5aa74f92c83

**Comment by bbhtt** [comment]
I guess these trackers served their purpose.
