### ISSUE TITLE
Tracker for applications using --filesystem=xdg-run/gvfs

### ISSUE THREAD

**Issue by hadess** [flathub/flathub#2180]
Starting with gvfs 1.48, GNOME [gvfs daemons will use an on-disk socket to communicate with `gvfsd` so that it will be possible to talk to gvfs while disabling the network](https://gitlab.gnome.org/GNOME/gvfs/-/issues/515). However, for applications to be able to talk through that on-disk socket, they need to be able to access it.

If your application talks directly to gvfs daemon, for example to list mounts, and access optical discs, then you will need to modify your application's manifest to include access to the `$XDG_RUNTIME_DIR/gvfsd`. For example, for a JSON manifest:
```
         "--talk-name=org.gtk.vfs", "--talk-name=org.gtk.vfs.*",
        "--filesystem=xdg-run/gvfs", "--filesystem=xdg-run/gvfsd",
```

If your application doesn't need to talk to gvfs via D-Bus, then it doesn't need access to `xdg-run/gvfsd`.

If you tried to access files using gvfs, and `gvfsd` was inaccessible, this error would be returned:
```
Error while getting peer-to-peer dbus connection: Could not connect: No such file or directory
```

 * [ ] [org.inkscape.Inkscape](https://github.com/flathub/org.inkscape.Inkscape)
 * [ ] [org.gnome.Lollypop](https://github.com/flathub/org.gnome.Lollypop)
 * [ ] [org.videolan.VLC](https://github.com/flathub/org.videolan.VLC)
 * [ ] [org.gimp.GIMP](https://github.com/flathub/org.gimp.GIMP)
 * [ ] [org.gnome.Totem](https://github.com/flathub/org.gnome.Totem)
 * [ ] [com.github.geigi.cozy](https://github.com/flathub/com.github.geigi.cozy)
 * [ ] [org.freefilesync.FreeFileSync](https://github.com/flathub/org.freefilesync.FreeFileSync)
 * [ ] [org.keepassxc.KeePassXC](https://github.com/flathub/org.keepassxc.KeePassXC)
 * [ ] [org.kde.krita](https://github.com/flathub/org.kde.krita)
 * [ ] [com.axosoft.GitKraken](https://github.com/flathub/com.axosoft.GitKraken)
 * [ ] [fr.handbrake.ghb](https://github.com/flathub/fr.handbrake.ghb)
 * [ ] [com.adobe.Flash-Player-Projector](https://github.com/flathub/com.adobe.Flash-Player-Projector)
 * [ ] [org.gnome.PasswordSafe](https://github.com/flathub/org.gnome.PasswordSafe)
 * [ ] [org.freecadweb.FreeCAD](https://github.com/flathub/org.freecadweb.FreeCAD)
 * [ ] [com.github.PintaProject.Pinta](https://github.com/flathub/com.github.PintaProject.Pinta)
 * [ ] [net.danigm.timetrack](https://github.com/flathub/net.danigm.timetrack)
 * [ ] [ml.prevete.Daty](https://github.com/flathub/ml.prevete.Daty)
 * [ ] [org.gnome.OCRFeeder](https://github.com/flathub/org.gnome.OCRFeeder)
 * [ ] [com.kristianduske.TrenchBroom](https://github.com/flathub/com.kristianduske.TrenchBroom)
 * [ ] [com.xnview.XnViewMP](https://github.com/flathub/com.xnview.XnViewMP)
 * [ ] [com.retrodev.blastem](https://github.com/flathub/com.retrodev.blastem)
 * [ ] [com.rawtherapee.RawTherapee](https://github.com/flathub/com.rawtherapee.RawTherapee)
 * [ ] [org.gnome.DejaDup](https://github.com/flathub/org.gnome.DejaDup)
 * [ ] [com.itopia.client](https://github.com/flathub/com.itopia.client)
 * [ ] [com.giuspen.cherrytree](https://github.com/flathub/com.giuspen.cherrytree)
 * [ ] [org.gnome.NetworkDisplays](https://github.com/flathub/org.gnome.NetworkDisplays)
 * [ ] [org.gnome.World.PikaBackup](https://github.com/flathub/org.gnome.World.PikaBackup)
 * [ ] [com.thincast.client](https://github.com/flathub/com.thincast.client)
 * [ ] [org.gnome.baobab](https://github.com/flathub/org.gnome.baobab)
 * [ ] [org.gnome.FileRoller](https://github.com/flathub/org.gnome.FileRoller)
 * [ ] [info.olasagasti.revelation](https://github.com/flathub/info.olasagasti.revelation)

**Comment by hadess** [comment]
GNOME Videos (`org.gnome.Totem`) fixed in https://github.com/flathub/org.gnome.Totem/pull/62

**Comment by Lctrs** [comment]
`com.axosoft.GitKraken` fixed in https://github.com/flathub/com.axosoft.GitKraken/commit/5f5685caa397df18f05fab9f6e84e69f58ba5c9e.
`org.gnome.NetworkDisplays` fixed in https://github.com/flathub/org.gnome.NetworkDisplays/commit/b190ce94d01a557d1de6b3d67392ba25c83c88a1.

**Comment by hadess** [comment]
Please be careful, if the application doesn't talk directly to gvfs, there's no need to add that hole. Eg. Krita doesn't need the change...

**Comment by gasinvein** [comment]
<details>
<summary>
Here is a complete list of apps with `--talk-name=org.gtk.vfs.*`, maybe it helps
</summary>

```
com.abisource.AbiWord
com.axosoft.GitKraken
com.github.alainm23.byte
com.github.alainm23.planner
com.github.artemanufrij.playmymusic
com.github.birros.WebArchives
com.github.calo001.fondo
com.github.geigi.cozy
com.github.horaciodrs.tradesim
com.github.junrrein.PDFSlicer
com.github.louis77.tuner
com.github.mdh34.quickdocs
com.github.needleandthread.vocal
com.github.philip_scott.notes-up
com.github.PintaProject.Pinta
com.giuspen.cherrytree
com.lettier.movie-monad
com.neatdecisions.Detwinner
com.rawtherapee.RawTherapee
com.transmissionbt.Transmission
com.usebottles.bottles
com.xnview.XnViewMP
cz.zeropage.Formiko
de.create3000.titania
dev.tchx84.Portfolio
edu.stanford.Almond
fr.handbrake.ghb
io.atom.Atom
io.brackets.Brackets
io.github.celluloid_player.Celluloid
io.github.dfandrich.gpscorrelate
org.darktable.Darktable
org.entangle_photo.Manager
org.free_astro.siril
org.freefilesync.FreeFileSync
org.gimp.GIMP
org.glimpse_editor.Glimpse
org.gnome.baobab
org.gnome.Builder
org.gnome.ColorViewer
org.gnome.DejaDup
org.gnome.Evince
org.gnome.FileRoller
org.gnome.font-viewer
org.gnome.gedit
org.gnome.Lollypop
org.gnome.Music
org.gnome.NetworkDisplays
org.gnome.Notes
org.gnome.OCRFeeder
org.gnome.PasswordSafe
org.gnome.Photos
org.gnome.Rhythmbox3
org.gnome.Shotwell
org.gnome.SoundJuicer
org.gnome.Totem
org.gnome.World.PikaBackup
org.gpodder.gpodder
org.inkscape.Inkscape
org.keepassxc.KeePassXC
org.libreoffice.LibreOffice
org.mozilla.firefox
org.onlyoffice.desktopeditors
org.remmina.Remmina
org.sparkleshare.SparkleShare
work.openpaper.Paperwork
```
</details>

**Comment by hadess** [comment]
Cozy doesn't need the change:
https://github.com/flathub/com.github.geigi.cozy/issues/4

DejaDup doesn't need the change:
https://github.com/flathub/org.gnome.DejaDup/issues/12

Handbrake fixed in https://github.com/flathub/fr.handbrake.ghb/commit/b5ac0a5a8e24704235af3688b8891e22e5894224

FreeCAD, timetrack, Daty, trenchboom, blastem, itopia, and thincast don't need the change.

**Comment by hfiguiere** [comment]
org.gimp.GIMP//stable is done

**Comment by hfiguiere** [comment]
org.inkscape.Inkscape//stable is done.

**Comment by hadess** [comment]
(We also found that `--talk-name=org.gtk.vfs` did nothing [because there wasn't ever a daemon with that name on the other side of the bus](https://github.com/flathub/org.gnome.DejaDup/issues/12#issuecomment-811976066), I'm not sure whether folks would appreciate me filing another tracker bug ^_^)

**Comment by hfiguiere** [comment]
com.rawtherapee.RawTherapee is done.

**Comment by hfiguiere** [comment]
com.rawtherapee.RawTherapee is done.

**Comment by bilelmoussaoui** [comment]
> (We also found that `--talk-name=org.gtk.vfs` did nothing [because there wasn't ever a daemon with that name on the other side of the bus](https://github.com/flathub/org.gnome.DejaDup/issues/12#issuecomment-811976066), I'm not sure whether folks would appreciate me filing another tracker bug ^_^)

I think it's fine to have another yet another tracker

**Comment by kparal** [comment]
org.freefilesync.FreeFileSync//stable is done

**Comment by hfiguiere** [comment]
Apparently AbiWord wasn't on the list, but it is being handled now.

**Comment by A6GibKm** [comment]
Fixed in baobab: https://github.com/flathub/org.gnome.baobab/pull/5
and in File Roller: https://github.com/flathub/org.gnome.FileRoller/pull/13

**Comment by A6GibKm** [comment]
Also in password safe: https://github.com/flathub/org.gnome.PasswordSafe/pull/9

**Comment by hfiguiere** [comment]
I forgot to mention I did org.gnome.OCRFeeder during an update. 

https://github.com/flathub/org.gnome.OCRFeeder/pull/21

**Comment by darkdragon-001** [comment]
Pinta fixed.

**Comment by hadess** [comment]
I've added documentation at https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access if anyone if still curious about the options.

**Comment by mwleeds** [comment]
> (We also found that `--talk-name=org.gtk.vfs` did nothing [because there wasn't ever a daemon with that name on the other side of the bus](https://github.com/flathub/org.gnome.DejaDup/issues/12#issuecomment-811976066), I'm not sure whether folks would appreciate me filing another tracker bug ^_^)

Maybe worth editing the description of this issue?
