### ISSUE TITLE
Tracker for apps with whole-bus DBus access

### ISSUE THREAD

**Issue by gasinvein** [flathub/flathub#2785]
Some apps on Flathub have `--socket=session-bus` and/or `--socket=system-bus`. Some development tools and DBus debuggers, like Bustle, actually need it to be useful, but **in most cases such permissions are overly broad and unnecessary**, and can and should be replaced with appropriate `--talk-name`/`--system-talk-name` permissions.

Here is a full list of apps with such permissions. Note that I didn't investigate each one if it actually needs the permission or not; just enumerating all of them.
- [x] app.moosync.moosync (system-bus) https://github.com/flathub/app.moosync.moosync/issues/1
- [x] com.github.eneshecan.WhatsAppForLinux (system-bus)
- [x] com.github.jkotra.eovpn (system-bus)
- [ ] com.github.naaando.lyrics (session-bus)
- [ ] com.hack_computer.Clubhouse (session-bus)
- [x] com.jetbrains.GoLand (session-bus)
- [x] com.jetbrains.PyCharm-Community (session-bus)
- [ ] com.jetbrains.PyCharm-Professional (session-bus)
- [ ] com.jetbrains.Rider (session-bus)
- [ ] com.jetbrains.RubyMine (session-bus)
- [x] com.powerball253.eternalmodmanager (session-bus) (https://github.com/flathub/com.powerball253.eternalmodmanager/pull/1)
- [x] com.rtosta.zapzap (system-bus, session-bus) https://github.com/flathub/com.rtosta.zapzap/issues/44
- [x] com.st.STM32CubeIDE (session-bus)
- [x] com.tutanota.Tutanota (system-bus, session-bus)
- [x] de.willuhn.Jameica (session-bus) (https://github.com/flathub/de.willuhn.Jameica/pull/18)
- [x] io.brackets.Brackets (system-bus, session-bus) ARCHIVED
- [x] io.github.betaflight.BetaflightConfigurator (system-bus)
- [ ] io.github.bothlab.syntalos (system-bus, session-bus)
- [x] io.freetubeapp.FreeTube (session-bus) (flathub/io.freetubeapp.FreeTube#64)
- [x] io.github.jliljebl.Flowblade (system-bus) https://github.com/flathub/io.github.jliljebl.Flowblade/pull/19
- [x] io.gitlab.jstest_gtk.jstest_gtk (session-bus) (https://github.com/flathub/io.gitlab.jstest_gtk.jstest_gtk/pull/5)
- [x] io.jamulus.Jamulus (system-bus)
- [x] io.qt.qdbusviewer (system-bus, session-bus)
- [x] net.displaycal.DisplayCAL (system-bus) https://github.com/flathub/net.displaycal.DisplayCAL/pull/4
- [ ] org.codeblocks.codeblocks (system-bus, session-bus)
- [ ] org.eclipse.Java (session-bus)
- [ ] org.eclipse.Javascript (session-bus)
- [ ] org.fcitx.Fcitx5 (session-bus)
- [x] org.freedesktop.Bustle (system-bus, session-bus)
- [x] org.gabmus.whatip (system-bus)
- [x] org.gnome.Builder (system-bus, session-bus)
- [x] org.gnome.dfeet (system-bus, session-bus)
- [x] org.gnome.dspy (system-bus, session-bus)
- [ ] org.xfce.ristretto (session-bus)
- [x] re.sonny.Workbench (session-bus)
- [x] vn.hoabinh.quan.CoBang (system-bus, session-bus) https://github.com/flathub/vn.hoabinh.quan.CoBang/commit/57b7170fcd4d96f8d005bb5e0f8f3b2846353c4e

**Comment by hfiguiere** [comment]
You can add https://github.com/flathub/com.rtosta.zapzap to the list. This was done post review / merge.

**Comment by gasinvein** [comment]
@hfiguiere Done. Btw I guess you have permissions to edit the list, too.

**Comment by hfiguiere** [comment]
No I don't.

**Comment by hfiguiere** [comment]
This one was just added:
https://github.com/flathub/app.moosync.moosync/commit/e1d77ec950adf2ce71a099ea5281fd1fb0b62135#commitcomment-75690570

**Comment by hfiguiere** [comment]
apparently fixed for moosync (can't mark it as such)

**Comment by gasinvein** [comment]
Two more added to the list: `com.powerball253.eternalmodmanager` and `re.sonny.Workbench`

**Comment by hfiguiere** [comment]
`net.displaycal.DisplayCAL` is done. Can't mark it as such.

**Comment by hfiguiere** [comment]
Flowblade PR https://github.com/flathub/io.github.jliljebl.Flowblade/pull/19

**Comment by hfiguiere** [comment]
Filed an issue for zapzap https://github.com/flathub/com.rtosta.zapzap/issues/44

**Comment by hfiguiere** [comment]
io.github.jliljebl.Flowblade was done.

**Comment by gasinvein** [comment]
Here flathub/com.github.eneshecan.WhatsAppForLinux@a86b471a4b59786a5943a27ccef8bef9a03c3671 we go again.

**Comment by barthalion** [comment]
This will be gated by the linter soon. Adding access to the socket or session bus without being listed in the exceptions first will be a hard CI failure.

**Comment by Tamaranch** [comment]
Hi, could [org.xfce.ristretto](https://github.com/flathub/org.xfce.ristretto) be added to the list of exceptions? #2770 is still not resolved, I just tried with `--talk-name` or `--own-name` locally and it still doesn't work, and the build now fails in CI: https://github.com/flathub/org.xfce.ristretto/pull/38.

Thanks!

**Comment by hongquan** [comment]
`vn.hoabinh.quan.CoBang` is solved.

**Comment by PowerBall253** [comment]
`com.powerball253.eternalmodmanager` is solved since [v3.0.0](https://github.com/flathub/com.powerball253.eternalmodmanager/commit/7cf501c75f96bf15ece295a74ca0edd6dec7a5e8).

**Comment by bbhtt** [comment]
This can be closed, this is blocked by the linter https://docs.flathub.org/docs/for-app-authors/linter#finish-args-arbitrary-dbus-access.
