### ISSUE TITLE
Applications with broken screenshots

### ISSUE THREAD

**Issue by barthalion** [flathub/flathub#3829]
After the recent outage, these applications are missing one or more screenshots:

- [x] app.drey.Blurble
- [ ] app.ytmdesktop.ytmdesktop
- [x] ar.com.tuxguitar.TuxGuitar
- [ ] com.arteeh.Flasher
- [x] com.authy.Authy
- [x] com.diy_fever.DIYLayoutCreator
- [x] com.github.labyrinth_team.labyrinth
- [x] com.github.needleandthread.vocal
- [x] com.github.raibtoffoletto.litteris
- [x] com.github.rajsolai.response
- [x] com.github.tmewett.BrogueCE
- [x] com.github.virtual_puppet_project.vpuppr
- [x] com.gitlab.jakobdev.jdnbtexplorer
- [ ] com.googleplaymusicdesktopplayer.GPMDP
- [x] com.mattermost.Desktop
- [x] com.rocksandpaper.syndic
- [x] com.roguetemple.HyperRogue
- [x] com.serveftp.officefactoring
- [x] com.sigmyne.crush
- [x] com.tracktion.Waveform
- [x] com.vagueentertainment.Framed
- [x] com.w1hkj.fldigi
- [x] com.w1hkj.flrig
- [x] de.halaszovich.PMbrowser
- [ ] dev.hdos.HDOS
- [x] edu.stanford.Almond
- [x] info.smplayer.SMPlayer
- [x] io.atom.Atom
- [x] io.gdevs.GDLauncher
- [x] io.github.betaflight.BetaflightConfigurator
- [x] io.github.seadve.Mousai
- [x] io.github.wereturtle.ghostwriter
- [x] io.jor.nanosaur
- [x] io.jor.ottomatic
- [x] net.sourceforge.Chessx
- [x] net.warsow.Warsow
- [x] net.xmind.XMind8
- [x] org.aliflang.lang
- [x] org.cloudcompare.CloudCompare
- [ ] org.gabmus.notorious
- [x] org.gephi.Gephi
- [x] org.gmusicbrowser.gmusicbrowser
- [x] org.gnome.Calculator
- [x] org.gnome.Fractal
- [x] org.gnome.GTG
- [x] org.gnome.meld
- [x] org.kde.Ikona
- [x] org.kiwix.desktop
- [x] org.librepcb.LibrePCB
- [x] org.libsdl.Maelstrom
- [x] org.mamedev.MAME
- [ ] org.megaglest.MegaGlest
- [x] org.mmass.mMass
- [x] org.openkj.OpenKJ
- [x] org.processing.processingide
- [x] org.pymol.PyMOL
- [x] org.solarus_games.solarus.Launcher
- [x] org.srb2.SRB2
- [x] org.srb2.SRB2Kart
- [x] org.twinery.Twine
- [x] org.unknown_horizons.UnknownHorizons
- [x] org.xiphos.Xiphos
- [x] pl.art.lach.slawek.V2BlankBrowser
- [x] uk.co.mangobrain.Infector

The original files are no longer accessible at the location specified in the appdata. We need to reach out to maintainers and ask them to fix it.

**Comment by hfiguiere** [comment]
For `ar.com.tuxguitar.TuxGuitar` the domain has been down for a few days (it's on my url watch list for update). Not sure if it is temporary or permanent.

**Comment by orowith2os** [comment]
com.inochi2d.inochi-creator seems to be broken ad well, I can fix the screenshots when I rework it to build from source (I already have a branch there containing my current work, just been a bit busy lately)

**Comment by Laserlicht** [comment]
@barthalion 

[io.github.ihhub.Fheroes2](https://flathub.org/apps/details/io.github.ihhub.Fheroes2) also has two (rather strange) broken files. But the original links are accessible, how to fix this?

**Comment by BigmenPixel0** [comment]
`org.getmonero.Monero` too.

**Comment by bbhtt** [comment]
Following 6 apps needs fixing, rest are fixed.

- [ ]  app.ytmdesktop.ytmdesktop
- [ ]  com.arteeh.Flasher
- [ ]  com.googleplaymusicdesktopplayer.GPMDP
- [ ]  dev.hdos.HDOS
- [ ]  org.gabmus.notorious
- [ ]  org.megaglest.MegaGlest

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/flathub/issues/3829#event-13387931720

@bbhtt, why is this closed as complete if some still need fixing?

**Comment by bbhtt** [comment]
> @bbhtt, why is this closed as complete if some still need fixing?

Because those last few are not being maintained and this will be caught by linter when they try to build. There's no need to track them separately.
