### ISSUE TITLE
[Tracking]: Apps with trademark violations

### ISSUE THREAD

**Issue by bbhtt** [flathub/flathub#5228]
- [ ] https://flathub.org/apps/io.github.mimbrero.WhatsAppDesktop
- [ ] https://flathub.org/apps/com.github.eneshecan.WhatsAppForLinux
- [ ] https://flathub.org/apps/com.ktechpit.whatsie
- [ ] https://flathub.org/apps/com.github.IsmaelMartinez.teams_for_linux
- [ ] https://flathub.org/apps/io.github.gamingdoom.Datcord
- [ ] https://flathub.org/apps/io.github.tdesktop_x64.TDesktop

**Comment by bbhtt** [comment]
Issues:

```
https://github.com/flathub/io.github.mimbrero.WhatsAppDesktop/issues/6
```

**Comment by lionirdeadman** [comment]
Maybe this would be worth adding to this list: https://flathub.org/apps/com.github.k4zmu2a.spacecadetpinball

**Comment by bbhtt** [comment]
What's the issue with that one?

**Comment by lionirdeadman** [comment]
It's a reverse-engineering Microsoft game using *Microsoft assets* https://en.wikipedia.org/wiki/Full_Tilt!_Pinball#3D_Pinball_for_Windows_%E2%80%93_Space_Cadet

**Comment by bbhtt** [comment]
That's a different issue than what this is tracking. 

Considering the original MS game is abandonware, the assets are publicly available all over the internet and it's being packaged as extra-data I don't think it's an issue for us at the moment.
